-- Created by Vertabelo (http://vertabelo.com)
-- Last modification date: 2023-04-11 01:41:26.979

-- foreign keys
ALTER TABLE CHASSI_SB
    DROP CONSTRAINT CHASSI_SB_CHASSI;

ALTER TABLE CHASSI_SB
    DROP CONSTRAINT CHASSI_SB_SERVICE_BULLETIN;

ALTER TABLE CHASSI
    DROP CONSTRAINT CHASSI_USER;

ALTER TABLE CHASSI_USER
    DROP CONSTRAINT CHASSI_USER_CHASSI;

ALTER TABLE CHASSI_USER
    DROP CONSTRAINT CHASSI_USER_USER;

ALTER TABLE CONDITIONAL_SBITE
    DROP CONSTRAINT CONDITIONAL_SBITE_FORMULA;

ALTER TABLE CONDITIONAL_SBITE
    DROP CONSTRAINT CONDITIONAL_SBITE_ITEM;

ALTER TABLE CONDITIONAL_SBITE
    DROP CONSTRAINT CONDITIONAL_SBITE_SB;

ALTER TABLE EDIT_USER_SB
    DROP CONSTRAINT EDIT_USER_SB_SERVICE_BULLETIN;

ALTER TABLE EDIT_USER_SB
    DROP CONSTRAINT EDIT_USER_SB_USER;

ALTER TABLE REGISTER_USER_ITEM
    DROP CONSTRAINT REGISTER_USER_ITEM_ITEM;

ALTER TABLE REGISTER_USER_ITEM
    DROP CONSTRAINT REGISTER_USER_ITEM_USER;

ALTER TABLE SERVICE_BULLETIN
    DROP CONSTRAINT SERVICE_BULLETIN_USER;

ALTER TABLE "USER"
    DROP CONSTRAINT USER_PERMISSION;

-- tables
DROP TABLE CHASSI;

DROP TABLE CHASSI_SB;

DROP TABLE CHASSI_USER;

DROP TABLE CONDITIONAL_SBITE;

DROP TABLE EDIT_USER_SB;

DROP TABLE FORMULA;

DROP TABLE ITEM;

DROP TABLE PERMISSION;

DROP TABLE REGISTER_USER_ITEM;

DROP TABLE SERVICE_BULLETIN;

DROP TABLE "USER";

-- End of file.

