CREATE SEQUENCE SEQ_AUTO_INCREMENT START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TR_AA_PERMISSION
BEFORE INSERT ON PERMISSION
FOR EACH ROW
BEGIN
  BEGIN
    SELECT SEQ_AUTO_INCREMENT.NEXTVAL INTO :new.PERMISSION_ID FROM dual;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      -- Tratar a exceção aqui
      -- Exemplo: definir o valor como 1
      :new.PERMISSION_ID := 1;
  END;
END;

CREATE OR REPLACE TRIGGER TR_AA_CHASSI
BEFORE INSERT ON CHASSI
FOR EACH ROW
BEGIN
  BEGIN
    SELECT SEQ_AUTO_INCREMENT.NEXTVAL INTO :new.CHASSI_ID FROM dual;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      -- Tratar a exceção aqui
      -- Exemplo: definir o valor como 1
      :new.CHASSI_ID := 1;
  END;
END;

CREATE OR REPLACE TRIGGER TR_AA_SERVICE_BULLETIN
BEFORE INSERT ON SERVICE_BULLETIN
FOR EACH ROW
BEGIN
  BEGIN
    SELECT SEQ_AUTO_INCREMENT.NEXTVAL INTO :new.SB_ID FROM dual;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      -- Tratar a exceção aqui
      -- Exemplo: definir o valor como 1
      :new.SB_ID := 1;
  END;
END;

CREATE OR REPLACE TRIGGER TR_AA_USER
BEFORE INSERT ON "USER"
FOR EACH ROW
BEGIN
  BEGIN
    SELECT SEQ_AUTO_INCREMENT.NEXTVAL INTO :new.USER_ID FROM dual;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      -- Tratar a exceção aqui
      -- Exemplo: definir o valor como 1
      :new.USER_ID := 1;
  END;
END;

CREATE OR REPLACE TRIGGER TR_AA_ITEM
BEFORE INSERT ON ITEM
FOR EACH ROW
BEGIN
  BEGIN
    SELECT SEQ_AUTO_INCREMENT.NEXTVAL INTO :new.ITEM_ID FROM dual;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      -- Tratar a exceção aqui
      -- Exemplo: definir o valor como 1
      :new.ITEM_ID := 1;
  END;
END;

CREATE OR REPLACE TRIGGER TR_AA_FORMULA
BEFORE INSERT ON FORMULA
FOR EACH ROW
BEGIN
  BEGIN
    SELECT SEQ_AUTO_INCREMENT.NEXTVAL INTO :new.FORMULA_ID FROM dual;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      -- Tratar a exceção aqui
      -- Exemplo: definir o valor como 1
      :new.FORMULA_ID := 1;
  END;
END;


CREATE OR REPLACE TRIGGER TR_AA_SB_CHASSI
BEFORE INSERT ON SB_CHASSI
FOR EACH ROW
BEGIN
  BEGIN
    SELECT SEQ_AUTO_INCREMENT.NEXTVAL INTO :new.SB_CHASSI_ID FROM dual;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      -- Tratar a exceção aqui
      -- Exemplo: definir o valor como 1
      :new.SB_CHASSI_ID := 1;
  END;
END;

CREATE OR REPLACE TRIGGER TR_AA_CHASSI_USER
BEFORE INSERT ON CHASSI_USER
FOR EACH ROW
BEGIN
  BEGIN
    SELECT SEQ_AUTO_INCREMENT.NEXTVAL INTO :new.CHASSI_USER_ID FROM dual;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      -- Tratar a exceção aqui
      -- Exemplo: definir o valor como 1
      :new.CHASSI_USER_ID := 1;
  END;
END;

CREATE OR REPLACE TRIGGER TR_AA_CONDITION_SBITEM
BEFORE INSERT ON CONDITION_SBITEM
FOR EACH ROW
BEGIN
  BEGIN
    SELECT SEQ_AUTO_INCREMENT.NEXTVAL INTO :new.CONDITION_ID FROM dual;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      -- Tratar a exceção aqui
      -- Exemplo: definir o valor como 1
      :new.CONDITION_ID := 1;
  END;
END;

CREATE OR REPLACE TRIGGER TR_AA_EDIT_USER_SB
BEFORE INSERT ON EDIT_USER_SB
FOR EACH ROW
BEGIN
  BEGIN
    SELECT SEQ_AUTO_INCREMENT.NEXTVAL INTO :new.EDIT_USER_SB_ID FROM dual;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      -- Tratar a exceção aqui
      -- Exemplo: definir o valor como 1
      :new.EDIT_USER_SB_ID := 1;
  END;
END;

CREATE OR REPLACE TRIGGER TR_AA_USER_ITEM
BEFORE INSERT ON USER_ITEM
FOR EACH ROW
BEGIN
  BEGIN
    SELECT SEQ_AUTO_INCREMENT.NEXTVAL INTO :new.USER_ITEM_ID FROM dual;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      -- Tratar a exceção aqui
      -- Exemplo: definir o valor como 1
      :new.USER_ITEM_ID := 1;
  END;
END;