-- tables
-- Table: CHASSI
CREATE TABLE CHASSI (
    CHASSI_ID integer,
    CHASSI_DTREGISTER timestamp  DEFAULT SYSDATE NOT NULL,
    CHASSI_STATUS char(1) DEFAULT 'A' NOT NULL, --mudei o tipo
    USER_ID_REGISTER integer  NOT NULL,
    CONSTRAINT PK_CHASSI_ID PRIMARY KEY (CHASSI_ID)
) ;

-- Table: SERVICE_BULLETIN
CREATE TABLE SERVICE_BULLETIN (
    SB_ID integer,
    SB_NAME varchar2(100)  NOT NULL, --ADICIONEI
    SB_DTREGISTER timestamp  DEFAULT SYSDATE NOT NULL,
    --sb_statusservice varchar2(15)  NOT NULL, REMOVI
    SB_PARTSERVICE varchar2(50),
    USER_ID_REGISTER integer  NOT NULL,
    CONSTRAINT PK_SERVICEBULLETIN PRIMARY KEY (SB_ID)
) ;

-- Table: PERMISSION
CREATE TABLE PERMISSION (
    PERMISSION_ID integer,
    PERMISSION_NAME varchar2(50)  NOT NULL,
    CONSTRAINT PK_PERMISSION PRIMARY KEY (PERMISSION_ID)
) ;

-- Table: USER
CREATE TABLE "USER" (
    USER_ID integer,
    USER_USERNAME varchar2(50)  NOT NULL, --MODIFIQUEI
    USER_PASSWORD varchar2(256)  NOT NULL, --MODIFIQUEI TAMANHO VARCHAR
    USER_STATUS char(1)  DEFAULT 'A' NOT NULL, --ACRESCENTEI
    PERMISSION_ID integer  NOT NULL,
    CONSTRAINT PK_USER PRIMARY KEY (USER_ID)
) ;

-- Table: ITEM
CREATE TABLE ITEM (
    ITEM_ID integer,
    ITEM_NAME varchar2(250)  NOT NULL,
    ITEM_DTREGISTER timestamp  DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_ITEM PRIMARY KEY (ITEM_ID)
) ;

-- Table: FORMULA
CREATE TABLE FORMULA (
    FORMULA_ID integer,
    FORMULA_DESC varchar2(250)  NOT NULL,
    CONSTRAINT FORMULA_pk PRIMARY KEY (formula_id)
) ;

-- Table: CHASSI_SB
CREATE TABLE SB_CHASSI (
    SB_CHASSI_ID integer,
    CHASSI_ID integer  NOT NULL,
    SB_ID integer  NOT NULL,
    SB_STATUSSERVICE varchar2(15), --ADICIONEI
    CONSTRAINT PK_SB_CHASSI PRIMARY KEY (SB_CHASSI_ID)
) ;

-- Table: CHASSI_USER
CREATE TABLE CHASSI_USER (
    CHASSI_USER_ID integer,
    CHASSI_ID integer  NOT NULL,
    USER_ID integer  NOT NULL,
    CONSTRAINT PK_CHASSI_USER PRIMARY KEY (CHASSI_USER_ID)
) ;

-- Table: CONDITION_SBITEM
CREATE TABLE CONDITION_SBITEM ( --MUDEI NOME DA TABELA
    CONDITION_ID integer,
    CONDITION_VAR varchar2(50)  NOT NULL,
    SB_ID integer  NOT NULL,
    FORMULA_ID integer  NOT NULL,
    ITEM_ID integer  NOT NULL,
    CONSTRAINT PK_CONDITION PRIMARY KEY (CONDITION_ID)
) ;

/* ITEM REMOVIDO DO BD

-- Table: EDIT_USER_SB
CREATE TABLE EDIT_USER_SB (
    EDIT_USER_SB_ID integer, -- MUDEI
    SB_ID integer  NOT NULL,
    USER_ID_EDIT integer  NOT NULL,
    CONSTRAINT PK_EDIT_USER_SB PRIMARY KEY (EDIT_USER_SB_ID)
) ;
*/

-- Table: USER_ITEM
CREATE TABLE USER_ITEM ( --MUDEI NOME
    USER_ITEM_ID integer,
    ITEM_ID integer  NOT NULL,
    USER_ID integer  NOT NULL,
    CONSTRAINT PK_USER_ITEM PRIMARY KEY (USER_ITEM_ID)
) ;

-- foreign keys
-- Reference: CHASSI_SB_CHASSI (table: CHASSI_SB)
ALTER TABLE SB_CHASSI ADD CONSTRAINT FK_SB_CHASSI_CHASSI
    FOREIGN KEY (CHASSI_ID)
    REFERENCES CHASSI (CHASSI_ID);

-- Reference: CHASSI_SB_SERVICE_BULLETIN (table: CHASSI_SB)
ALTER TABLE SB_CHASSI ADD CONSTRAINT FK_SB_CHASSI_SB
    FOREIGN KEY (SB_ID)
    REFERENCES SERVICE_BULLETIN (SB_ID);

-- Reference: CHASSI_USER_CHASSI (table: CHASSI_USER)
ALTER TABLE CHASSI_USER ADD CONSTRAINT FK_CHASSI_USER_CHASSI
    FOREIGN KEY (CHASSI_ID)
    REFERENCES CHASSI (CHASSI_ID);

-- Reference: CHASSI_USER_USER (table: CHASSI_USER)
ALTER TABLE CHASSI_USER ADD CONSTRAINT FK_CHASSI_USER_USER
    FOREIGN KEY (USER_ID)
    REFERENCES "USER" (USER_ID);

-- Reference: CONDITIONAL_SBITE_FORMULA (table: CONDITIONAL_SBITE)
ALTER TABLE CONDITION_SBITEM ADD CONSTRAINT FK_CONDITION_SBITEM_FORMULA
    FOREIGN KEY (FORMULA_ID)
    REFERENCES FORMULA (FORMULA_ID);

-- Reference: CONDITIONAL_SBITE_ITEM (table: CONDITIONAL_SBITE)
ALTER TABLE CONDITION_SBITEM ADD CONSTRAINT FK_CONDITION_SBITEM_ITEM
    FOREIGN KEY (ITEM_ID)
    REFERENCES ITEM (ITEM_ID);

-- Reference: CONDITIONAL_SBITE_SB (table: CONDITIONAL_SBITE)
ALTER TABLE CONDITION_SBITEM ADD CONSTRAINT FK_CONDITION_SBITEM_SB
    FOREIGN KEY (SB_ID)
    REFERENCES SERVICE_BULLETIN (SB_ID);

/* ITEM REMOVIDO DO BD

-- Reference: EDIT_USER_SB_SERVICE_BULLETIN (table: EDIT_USER_SB)
ALTER TABLE EDIT_USER_SB ADD CONSTRAINT FK_EDIT_USER_SB_SB
    FOREIGN KEY (SB_ID)
    REFERENCES SERVICE_BULLETIN (SB_ID);

-- Reference: EDIT_USER_SB_USER (table: EDIT_USER_SB)
ALTER TABLE EDIT_USER_SB ADD CONSTRAINT FK_EDIT_USER_SB_USER
    FOREIGN KEY (USER_ID_EDIT)
    REFERENCES "USER" (USER_ID);
*/

-- Reference: REGISTER_USER_ITEM_ITEM (table: REGISTER_USER_ITEM)
ALTER TABLE USER_ITEM ADD CONSTRAINT FK_USER_ITEM_ITEM
    FOREIGN KEY (ITEM_ID)
    REFERENCES ITEM (ITEM_ID);

-- Reference: REGISTER_USER_ITEM_USER (table: REGISTER_USER_ITEM)
ALTER TABLE USER_ITEM ADD CONSTRAINT FK_USER_ITEM_USER
    FOREIGN KEY (USER_ID)
    REFERENCES "USER" (USER_ID);

-- Reference: SERVICE_BULLETIN_USER (table: SERVICE_BULLETIN)
ALTER TABLE SERVICE_BULLETIN ADD CONSTRAINT FK_SB_USER
    FOREIGN KEY (USER_ID_REGISTER)
    REFERENCES "USER" (USER_ID);

-- Reference: USER_PERMISSION (table: USER)
ALTER TABLE "USER" ADD CONSTRAINT FK_USER_PERMISSION
    FOREIGN KEY (PERMISSION_ID)
    REFERENCES PERMISSION (PERMISSION_ID);

-- End of file.

